### ISSUE TITLE
Fix error processing issue

### ISSUE THREAD

**Issue by laurigates** [laurigates/gha-issue-resolution#6]
An error occurred while processing this issue: Error processing issue #2: 422 {"message": "Validation Failed", "errors": [{"resource": "PullRequest", "code": "custom", "message": "No commits between main and fix-issue-2"}], "documentation_url": "https://docs.github.com/rest/pulls/pulls#create-a-pull-request", "status": "422"}

**Comment by laurigates** [comment]
## AI-generated suggestion

    Here's a potential solution to this issue, generated by an AI assistant:

    The problem stems from the GitHub Actions workflow attempting to create a pull request before any commits exist on the `fix-issue-2` branch.  The solution necessitates ensuring the workflow creates the branch, makes commits to it, pushes those commits, and *then* creates the pull request.  We'll need to modify the `issue_resolution.yml` file.  Since the exact contents aren't provided, I'll offer a solution assuming a common workflow structure.  Adapt this to your specific workflow.


**1. Detailed Solution (with example code changes):**

Let's assume your `issue_resolution.yml` uses a Python script (`src/gha_issue_resolution/__main__.py`) to handle the logic.  The following demonstrates how to modify the workflow and the Python script.


**`.github/workflows/issue_resolution.yml` (Modified):**

```yaml
name: Issue Resolution Workflow

on:
  issues:
    types: [opened]

jobs:
  resolve-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run issue resolution script
        run: python src/gha_issue_resolution/__main__.py ${{ github.event.issue.number }}

      - name: Create Pull Request
        uses: peter-evans/create-or-update-pull-request@v4
        with:
          title: "Fix issue #${{ github.event.issue.number }}"
          body: "This pull request resolves issue #${{ github.event.issue.number }}"
          base: main
          head: fix-issue-${{ github.event.issue.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**`src/gha_issue_resolution/__main__.py` (Modified):**

```python
import subprocess
import sys

def resolve_issue(issue_number):
    branch_name = f"fix-issue-{issue_number}"

    # 1. Create the branch
    try:
        subprocess.run(['git', 'checkout', '-b', branch_name, 'main'], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error creating branch: {e}")
        sys.exit(1)


    #2. Make a commit (replace with your actual code changes)
    try:
        with open("temp_file.txt", "w") as f:
            f.write(f"Commit for issue {issue_number}")
        subprocess.run(['git', 'add', 'temp_file.txt'], check=True)
        subprocess.run(['git', 'commit', '-m', f'Fix issue {issue_number}'], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error committing changes: {e}")
        sys.exit(1)

    # 3. Push the branch
    try:
        subprocess.run(['git', 'push', 'origin', branch_name], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error pushing branch: {e}")
        sys.exit(1)


if __name__ == "__main__":
    issue_number = sys.argv[1]
    resolve_issue(issue_number)

```

**2. Explanation:**

* The `issue_resolution.yml` workflow now explicitly calls a Python script to handle branch creation and commit.  The `peter-evans/create-or-update-pull-request` action is used to create the pull request.  Crucially, it only attempts to create the PR *after* the Python script has completed successfully.

* The `__main__.py` script does the following:
    * Creates a new branch (`fix-issue-${issue_number}`) from `main`.
    * Makes a dummy commit (replace `"Commit for issue..."` with your actual code changes for issue resolution).  It's essential to have *at least one* commit for the PR to work.
    * Pushes the new branch to the remote repository.

This ensures that a branch with commits exists before the pull request creation is attempted, thereby resolving the "No commits" error.


**3. Potential Side Effects and Considerations:**

* **Error Handling:**  The provided Python script includes basic error handling.  More robust error handling (logging, more specific error messages) should be added for production use.
* **Commit Message:** The commit message is currently generic.  Make it more descriptive and relevant to the actual changes made.
* **Code Changes:** The placeholder commit in `__main__.py` needs to be replaced with the actual code that fixes the issue.  This part is heavily context-dependent and requires understanding your codebase and the specific issue.
* **Security:**  Never hardcode sensitive information (like API keys or tokens) directly in your workflow files. Use GitHub Secrets to store and access sensitive data securely.
* **Dependency Management:** Ensure that all necessary libraries are listed in `requirements.txt`.
* **Testing:** Thoroughly test the workflow after making these changes in a development environment before deploying it to your main repository.


Remember to adapt the code to your specific needs and context.  The provided solution is a template; you must replace the placeholder commit with the actual code that resolves the issue.  Always back up your workflow files before making significant changes.


    Please review this suggestion and let me know if you need any clarification or have any questions.
    This is an AI-generated response and may require human validation and testing before implementation.
